<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>012173D_ALSN4</name>
   <tag></tag>
   <elementGuidId>3c1f09ea-1943-4ab9-a5a7-80dba2a6115a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@class = 'android.widget.TextView' and (text() = 'Debitur tidak memiliki gaya hidup atau  permasalahan pribadi yang dapat mengurangi kemampuan membayar kredit pada saat ini dan masa mendatang.' or . = 'Debitur tidak memiliki gaya hidup atau  permasalahan pribadi yang dapat mengurangi kemampuan membayar kredit pada saat ini dan masa mendatang.') and @resource-id = 'id.co.bri.brispotnew:id/cb_jawaban']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>android.widget.TextView</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Debitur tidak memiliki gaya hidup atau  permasalahan pribadi yang dapat mengurangi kemampuan membayar kredit pada saat ini dan masa mendatang.</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>resource-id</name>
      <type>Main</type>
      <value>id.co.bri.brispotnew:id/cb_jawaban</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>package</name>
      <type>Main</type>
      <value>id.co.bri.brispotnew</value>
   </webElementProperties>
</WebElementEntity>
