<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>012195H_ALSN8</name>
   <tag></tag>
   <elementGuidId>85edb889-40c1-4c47-a5c5-2be24da66eae</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@class = 'android.widget.TextView' and (text() = 'Debitur memiliki garansi dari pemrintah atau dari perusahaan dengan rating AAA sampai dengan investment grade atau Anjak Piutang dan/atau resi gudang mengcover > 100%' or . = 'Debitur memiliki garansi dari pemrintah atau dari perusahaan dengan rating AAA sampai dengan investment grade atau Anjak Piutang dan/atau resi gudang mengcover > 100%') and @resource-id = 'id.co.bri.brispotnew:id/cb_jawaban']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>android.widget.TextView</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Debitur memiliki garansi dari pemrintah atau dari perusahaan dengan rating AAA sampai dengan investment grade atau Anjak Piutang dan/atau resi gudang mengcover > 100%</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>resource-id</name>
      <type>Main</type>
      <value>id.co.bri.brispotnew:id/cb_jawaban</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>package</name>
      <type>Main</type>
      <value>id.co.bri.brispotnew</value>
   </webElementProperties>
</WebElementEntity>
