<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>012181A_ALSN1</name>
   <tag></tag>
   <elementGuidId>0fa480c1-bf6a-4b91-b728-5e867ff31f66</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@class = 'android.widget.TextView' and (text() = 'Terdapat informasi negatif dari supplier/ pelanggan/ perusahaan sejenis namun tidak dapat dijelaskan oleh nasabah disertai bukti yang memadai' or . = 'Terdapat informasi negatif dari supplier/ pelanggan/ perusahaan sejenis namun tidak dapat dijelaskan oleh nasabah disertai bukti yang memadai') and @resource-id = 'id.co.bri.brispotnew:id/cb_jawaban']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>android.widget.TextView</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Terdapat informasi negatif dari supplier/ pelanggan/ perusahaan sejenis namun tidak dapat dijelaskan oleh nasabah disertai bukti yang memadai</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>resource-id</name>
      <type>Main</type>
      <value>id.co.bri.brispotnew:id/cb_jawaban</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>package</name>
      <type>Main</type>
      <value>id.co.bri.brispotnew</value>
   </webElementProperties>
</WebElementEntity>
